owner: samankhalife
repo: upptime
user-agent: samankhalife

sites:
  - name: Main Website
    url: https://samankhalife.ir/

  - name: Wikipedia
    url: https://en.wikipedia.org

  - name: POST to Google
    url: https://www.google.com
    method: POST

  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53

  - name: Google DNS
    check: "tcp-ping"
    url: dns.google
    port: 53

  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: upptime.samankhalife.ir
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Saman
  introTitle: "Saman"
  introMessage: Upptime Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

